Set Expressions (with Chainable Format) for Arithmetic and Relational Operations
chocoteam/choco-solver pull request #1107
Opened 2024-10-22 04:18 UTC by gadavidd

**Set Expressions (with Chainable Format) for Arithmetic and Relational Operations**

I've been working with `SetVar` in `choco-Solver`. Unlike other types of variables, such as `RealVar` or `IntVar`, there was no direct way to compose operations such as equals (eq), not equals (ne), contains, not contains (nc), subset (subSet), union, or intersection directly in the model definition. While propagators allow for constructing such constraints, it was not as intuitive as it is for other variable types like `IntVar` and `RealVar`. These features are extremely useful in facilitating the composition of constraints.

Thus, I've worked on adding this feature for `SetVar`, based on the operations already available for other variable types. For example:

```java
realVar.eq(3).post();
```

However, such expressions were not possible for `SetVar`:

```java
setVar.eq(1, 2, 3).post();  // Not available... until now!
```

**Improvement**

I've implemented a new expression framework for `SetVar`, allowing the use of familiar operations directly on set variables. This change introduces support for the following operations:

Relational Operations:

- `eq` (Equals): `setA.eq(1, 2, 3)` or `setA.eq(setB)`.
- `ne` (Not Equals): `setA.ne(1, 2)` or `setA.ne(setB)`.
- `contains`: `setA.contains(1, 2)`.
- `nc` (notContains): `setA.notContains(1, 2)`.
- `subSet`: `setA.subSet(1, 2, 3)` or `setA.subSet(setB)`.

Arithmetic Set Operations:

`union`: `setA.union(setB)`
`intersection`: `setA.intersection(setB)`

This enhancement allows for the expression of complex set relations with simplified syntax, enabling combinations such as:

```java
setA.eq(setB.union(setC.intersection(setD))).post();
```

**Example Usage:**
```java
Model model = new Model();

// Define set variables
SetVarImplArExpression setA = new SetVarImplArExpression(model, "setA", new int[]{}, new int[]{0, 1, 2, 3});
SetVarImplArExpression setB = new SetVarImplArExpression(model, "setB", new int[]{}, new int[]{1, 2, 3});
SetVarImplArExpression setC = new SetVarImplArExpression(model, "setC", new int[]{}, new int[]{2, 3, 4, 5});

// Compose set expressions
setA.eq(setB.union(setC)).post();
model.getSolver().propagate();

// Assert the expected values in setA
assertTrue(Arrays.equals(setA.getUB().toArray(), new int[]{1, 2, 3, 4, 5}));
```

**Internal Changes:**

This change is implemented through three main components:

- Unary Set Expressions (`UnReSetExpression`): Handle relations between a set and a list of values, like `setVar.eq(1,2,3).post()`.
- Binary Set Expressions (`BiReSetExpression`): Manage operations between two `SetVar` instances, such as `setA.eq(setB).post()`.
- Binary Arithmetic Expressions (`BiArSetExpression`): Handle arithmetic operations like unions and intersections, e.g., `setA.eq(setB.union(setC)).post()`.

A new interface, `SetExpression`, inspired by other Choco-Solver expressions, allows `SetVarExpression` to be used in conjunction with these expression composition objects (`UnReSetExpression`, `BiReSetExpression`, and `BiArSetExpression`).

**Backward Compatibility:**

This improvement is fully backward-compatible with existing constraints and models. It adds considerable flexibility when working with `SetVar`, and I believe it will make modeling with sets much more intuitive.

**Future Improvements:**

I believe that additional operations, such as disjoint, could also be implemented to further enhance set operations in Choco-Solver.

Finally, I've included a comprehensive suite of tests in `SetVarExpressionTest`, which I hope will be useful to validate this enhancement.

I would greatly appreciate any feedback or suggestions for optimizations, as well as any edge cases that could further improve this approach!

2024-11-05 09:07 UTC, cprudhom commented
Thank you for the PR. 
It's in my TODOs but I'd like to finish another task before starting on this one, which I think is absolutely relevant.

2025-01-08 16:39 UTC, cprudhom requested changes

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +                    result = model.subsetEq(xSet, ySet).reify().eq(TRUE).boolVar();
The expected expression is : `(xSet \in ySet) \impl result` but you defined: `((xSet \in ySet) \impl True) \imp result`.
You can simplify the expression to:
```java
result = model.subsetEq(xSet, ySet).reify();
```

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +import static org.chocosolver.solver.constraints.real.Ibex.TRUE;
`Ibex.TRUE` is a constant for continuous constraint programming and should not be used in Set expressions

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +                    result = model.allEqual(xSet, ySet).reify().eq(TRUE).boolVar();
same as l.55

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +                    result = model.subsetEq(ySet, xSet).reify().eq(TRUE).boolVar();
same as l.55

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +                    result = model.allDifferent(xSet, ySet).reify().eq(TRUE).boolVar();
same as l.55

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +                    result = model.disjoint(ySet, xSet).reify().eq(TRUE).boolVar();
same as l.55

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/SetExpression.java
> +    default SetExpression union(SetExpression y){
I suppose we can have JavaDoc here

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +    }
I would throw an exception here, to be safe

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/UnReSetExpression.java
> +    public UnReSetExpression(SetOperator operator, SetExpression x, int... y) {
I'm not sure to understand why this class is needed, everything can be done with `BiReSetExpression`, no?

2025-01-08 16:39 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/variables/impl/SetVarExpression.java
> +public class SetVarExpression extends SetVarImpl implements SetExpression {
I don't think this class is useful, can't SetVar implement SetExpression directly?

2025-03-20 18:47 UTC, gadavidd commented on solver/src/main/java/org/chocosolver/solver/variables/impl/SetVarExpression.java
> +public class SetVarExpression extends SetVarImpl implements SetExpression {
I initially considered modifying `SetVar` directly, but this approach introduced conflicts due to method inheritance ( `getModel()` ) and could lead to potential breaking changes. Instead, `SetVarExpression` provides a clean abstraction without modifying core components. However, we can consider this change, though it may impact all classes that inherit from SetVar. Would that be a concern?

I initially thought that `SetVarExpression` would only replace `SetVarImpl`, reducing the overall impact. However, I'm open to whatever is best for choco-solver

2025-03-20 18:48 UTC, gadavidd commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +                    result = model.subsetEq(xSet, ySet).reify().eq(TRUE).boolVar();
Updated as suggested

2025-03-20 18:48 UTC, gadavidd commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +import static org.chocosolver.solver.constraints.real.Ibex.TRUE;
Updated as suggested

2025-03-20 18:49 UTC, gadavidd commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/SetExpression.java
> +    default SetExpression union(SetExpression y){
Updated as suggested. See if it is in accordance with the added documentation, if anything I can change it again. I tried to follow the standard adopted in the project.

2025-03-20 18:49 UTC, gadavidd commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/BiReSetExpression.java
> +    }
Exception added

2025-03-20 18:51 UTC, gadavidd commented on solver/src/main/java/org/chocosolver/solver/expression/discrete/set/UnReSetExpression.java
> +    public UnReSetExpression(SetOperator operator, SetExpression x, int... y) {
I tried to separate the classes according to responsibility. One for handling the relationship between set and literal value and another for set with set. But I can join them.

2025-03-20 18:53 UTC, gadavidd commented on solver/src/main/java/org/chocosolver/solver/variables/impl/SetVarExpression.java
> +public class SetVarExpression extends SetVarImpl implements SetExpression {
Also, I'm sorry, I think it would have been appropriate to have sent you the changes already considering version 5.0.0-beta.1, I will do this in the next corrections.

2025-08-29 08:47 UTC, cprudhom commented
Now in #1171

2025-08-29 08:47 UTC, closed without merging