A pure java alternative for power operations with integer positive exponents
chocoteam/choco-solver pull request #723
Opened 2020-09-09 14:19 UTC by schmittjoaopedro

Changes proposed in this PR:
- Add a pure java alternative for power operations with integer positive exponents.
- Add tests to increase the coverage of expected results for power operations (some of these tests are waiting the release of the contraction ratio parameter in ibex)
 
@chocoteam/core-developer

2020-09-15 12:53 UTC, cprudhom requested changes
Thank you for contributing.
Here are my general comments.
1. Nice test suite, thanks!
2. The propagator is OK to me, but I do not agree with the way it is used:
- `RealVar realVar(double p)` is supposed to be used exclusively with Ibex
- Commonly, mixed constraints (ie, continuous and discrete) are declared in `IRealConstraintFactory`.
Consequently, I think the code should be revamped.
3. I don't think adding new methods to `RealUtils` is required too.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> + * <p>
The 3 following lines are out-dated, there is no reference to `jinterval` anymore, if I'm correct.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +public class RealPowerPropagator extends Propagator<RealVar> {
In Choco, we name propagator with prefix `Prop`.
You could change the name to `PropRealPower`.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +    private RealVar yVar;
can be final

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +    private RealVar xVar;
can be final

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +    private int k;
can be final

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +            lb = RealUtils.roundValue(lb, xVar.getPrecision());
Why not calling `RealUtils.prevFloat` ?

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +            ub = RealUtils.roundValue(ub, xVar.getPrecision());
Why not calling `RealUtils.nextFloat` ?

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +        RealInterval x = new RealIntervalConstant(xVar.getLB(), xVar.getUB());
`xVar` extends `RealInterval`, creating a `RealIntervalConstant ` is not necessary.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +        y = RealUtils.updateBounds(y, power);
Previous lines, including this one, can be replaced by:
```java
RealInterval y = RealUtils.updateBounds(yVar, RealUtils.iPower(xVar, k));
```

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/constraints/real/RealPowerPropagator.java
> +        RealInterval x = new RealIntervalConstant(xVar.getLB(), xVar.getUB());
The method can also be simplified, using already existant API:
```java
boolean isIntervalPositive = xVar.getLB() >= 0;
boolean isIntervalNegative = xVar.getUB() <= 0;
RealInterval root = RealUtils.iRoot(yVar, k); // x = root(y, k)
boolean isEven = k % 2 == 0;
// In all cases, bounds ar calculate as intersection between x and temp
if (isEven) {
    if (isIntervalPositive) {
        return xVar.updateBounds(root.getLB(), root.getUB(), this);
    } else if (isIntervalNegative) {
        return xVar.updateBounds(-root.getUB(), -root.getLB(), this);
    } else { // It's crossing zero
        return xVar.updateBounds(-root.getUB(), root.getUB(), this);
    }
} else {
    // For odd roots isn't necessary specific handling as roots can be negative naturally
    return xVar.updateBounds(root.getLB(), root.getUB(), this);
}
```

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/continuous/arithmetic/CstCArExpression.java
> +package org.chocosolver.solver.expression.continuous.arithmetic;
Why this new classe is needed?
I think everything can be moved to `BiCArExpression`.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/continuous/arithmetic/CstCArExpression.java
> +                            me = model.realVar(powerResult.getLB(), powerResult.getUB(), xVar.getPrecision());
I'm quite uncomfortable with this. 
The `RealVar realVar(double p)` is supposed to deal with stuff for Ibex. But here, you are doing something different. 
If we want this to be coherent with wath already exists, I would suggest to move the constraint declaration in `IRealConstraintFactory`. 
The power constraint will then be called directly from there.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/util/tools/RealUtils.java
> +    public static RealInterval updateBounds(RealInterval var, RealInterval newInterval) {
this method already exists for `RealVar` and it not required anymore with the correction I suggested.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/util/tools/RealUtils.java
> +    public static RealInterval updateBounds(RealInterval var, double lb, double ub) {
Same comment as previous one.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/util/tools/RealUtils.java
> +    public static double roundValue(double value, double precision) {
That seems strange to me to pass by a `String` to get a double.
I think calling `prevFloat` and `nextFloat` are enough in `isEntailed`

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/continuous/arithmetic/CArExpression.java
> +        return new CstCArExpression(CArExpression.Operator.POW, this, y);
As I said, I don't think `CstCArExpression` is needed.

2020-09-15 12:53 UTC, cprudhom commented on solver/src/main/java/org/chocosolver/solver/expression/continuous/arithmetic/UnCArExpression.java
> +    CArExpression e;
I believe this modification is not needed anymore if `CstCArExpression` disappears.

2020-09-15 19:02 UTC, schmittjoaopedro commented
All right, I see all your points and I will revise all of them.
However right now I'm very busy with other stuffs, but in the meantime I was thinking in create another pull request to just contribute with the test suite. I think it's very important and don't want to let it in standby (outside from the master branch) until I came back to continue the development.

What do you think?

2020-09-16 15:32 UTC, cprudhom commented
Sure, you can split the PR in 2

2020-09-17 01:31 UTC, schmittjoaopedro commented
I've created the PR #723 to segregate the test suite and propose some improvements for ibex integration.

About this PR, I was wondering and I agree that it's not a good idea to replace the ibex integration with a new propagator, because it would reduce the expected homogeneous behavior of IBEX. I think that a better solution should be follow the guidelines of the H4C algorithm implementing the `tighten` and `project` methods.

I'll not have time to think about that now, so I will close this PR for while.

2020-09-17 01:31 UTC, closed without merging